# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: aws-account
  description: This component is responsible for provisioning the full account hierarchy along with Organizational Units (OUs)
  homepage: https://cloudposse.com/accelerate
  topics: terraform, terraform-component







